// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://enmtpjatwkvptijqsngg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVubXRwamF0d2t2cHRpanFzbmdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MzczNzUsImV4cCI6MjA2ODUxMzM3NX0.Q1gVsE7hDnod-v64Sf8WUud-rGfOHr0iP5ymbJ_V898";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});